<?php

/**
 *
 * Image To Markdown
 *
 * @author Robin Sallis
 *
 * ProcessWire 3.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class ImageToMarkdown extends WireData implements Module {

	/**
	 * Module information
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Image To Markdown',
			'summary' => 'Alt+click an image in Page Edit to copy an image markdown string to clipboard.',
			'version' => '0.1.0',
			'author' => 'Robin Sallis',
			'href' => 'https://github.com/Toutouwai/ImageToMarkdown',
			'icon' => 'picture-o',
			'autoload' => 'template=admin',
		);
	}

	/**
	 * Ready
	 */
	public function ready() {
		$this->addHookAfter('ProcessPageEdit::execute', $this, 'addScript');
	}

	/**
	 * Add script
	 *
	 * @param HookEvent $event
	 */
	public function addScript(HookEvent $event) {
		// Return if ProcessPageEdit is being loaded via AJAX (image field)
		if($this->config->ajax) return;

		// Add JS
		$config = $this->config;
		$info = $this->getModuleInfo();
		$version = $info['version'];
		$config->scripts->add("{$config->urls->$this}{$this}.js?v={$version}");
	}

}
